version: "3"
services:
  ynabdoctor:
    image: ynabdoctor
    container_name: ynabdoctor
    build: .
    environment:
      accessToken: "${YNAB_ACCESS_TOKEN}"
      mongoUrl: 'mongodb://mongo:27017/ynabreporting'
      mongoDBName: 'YNABDoctor'
      budgetName: '${YNAB_BUDGET_NAME}'
    ports:
      - "62818:8080"
    command: ["/usr/src/wait-for-it/wait-for-it.sh", "mongo:27017", "--",  "npm", "start"]
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: ynabdoctor_mongo
    restart: always
